### ISSUE TITLE
Can’t increase stat by clicking after modifying value

### ISSUE THREAD

**Issue by fromcj** [mikehodgson/tsmt#7]
If you use the pencil icon to modify an icon (e.g. to change a new mission # without clicking 135 times) then a 1 will just be added to the end of the number instead. 

ex. You change a new stat from 0 to 80 with the pencil icon. Then you click the stat to increase and it becomes 801.

**Comment by mikehodgson** [comment]
This has been fixed in the latest commit. You might need to refresh the page to pick up changes.
